### ISSUE TITLE
Remove unbeneficial state setter methods

### ISSUE THREAD

**Issue by lakeboerg** [andrej5000/TicTacToe#10]
In the `App` currently the game width and height are set in separate functions being passed down to the `Config` component.

When doing so and it is the only operation to be executed, it is completely sufficient to use an anonymous function, e.g.:

```
...
<CallbackReceivingComponent
    onUpdateKnownField={(localStateKeyName) => ::this.setState({ localStateKeyName })}
/>
...
```

**Comment by andrej5000** [comment]
Fixed
