### ISSUE TITLE
GameRaster - Don't pass the parent component's state as is in by reference

### ISSUE THREAD

**Issue by lakeboerg** [andrej5000/TicTacToe#6]
The state object is being passed as is (by reference) into the `ConfigComponent`. That is a bad practice because as:

* Firstly the whole state is exposed though not everything is required
* Secondly and most importantly, you can change the state in the `ConfigComponent` and that modifies the state in the parent `TicTacToe` component but not going through the React state change cycle.

Much cleaner, less error prone is to just pass down callbacks for specific value changes e.g.  `onChangeGameRasterWidth` (or `onGameRasterWidthChange`) and just call those props appropriately as callbacks from your input components.

This way, no state internals like key names are exposed.

**Comment by andrej5000** [comment]
Fixed
