### ISSUE TITLE
TicTacToe/ConfigComponent state data responsibilities/confusion

### ISSUE THREAD

**Issue by lakeboerg** [andrej5000/TicTacToe#8]
The following state data can be optimized

* `maxRasterDimension` in `TicTacToe` can reside either in `ConfigComponent` as constant; no need for state because it's never modified
* `initialCellValue` can be a constant; never modified
* consolidate configurations in state `config` key

In the end the state should be appropriately cut and specific to the component it is defined in. (see other issue regarding component split)

**Comment by andrej5000** [comment]
Fixed
