### ISSUE TITLE
Improve separation of concerns over components

### ISSUE THREAD

**Issue by lakeboerg** [andrej5000/TicTacToe#9]
Currently the (wrongly named `App` file) `TicTacToe` component contains of at least two higher responsibilities:

* Application control
* Game mechanics

This can be optimized to split it (as the names are heavily indicating):

* `App` (file and component, now the names and meanings do match again, yay)
** In which state is the current session (start/configuration, active game, finished game)
* `TicTacToe`
** Game mechanics reside here, not deciding whether to show the `Config` etc, but only the game.

And to address the question:
If a game is e.g. finished, then the `TicTacToe` component can receive an e.g. `onGameFinished` callback as a prop and so on.

**Comment by andrej5000** [comment]
Fixed
